# Generated by Django 4.1.7 on 2023-03-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eBirth_reg", "0002_birthregistration_hospitaladminprofile_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="birthregistration",
            options={"verbose_name_plural": "Birth Registrations"},
        ),
        migrations.AlterModelOptions(
            name="hospitaladminprofile",
            options={"verbose_name_plural": "Hospital Admin Profile"},
        ),
        migrations.AlterModelOptions(
            name="hospitalprofile", options={"verbose_name_plural": "Hospital Profile"},
        ),
        migrations.AlterModelTable(
            name="birthregistration", table="Birth Registration",
        ),
        migrations.AlterModelTable(
            name="hospitaladminprofile", table="Hospital Admin Profile",
        ),
        migrations.AlterModelTable(name="hospitalprofile", table="Hospital Profile",),
    ]
