# Generated by Django 4.1.7 on 2023-03-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eBirth_reg", "0003_alter_birthregistration_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender_title", models.CharField(max_length=7)),
            ],
            options={"verbose_name_plural": "Gender", "db_table": "Gender",},
        ),
        migrations.RemoveField(model_name="birthregistration", name="delivered_by",),
        migrations.AddField(
            model_name="birthregistration",
            name="gender",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="eBirth_reg.gender",
            ),
            preserve_default=False,
        ),
    ]
