# Generated by Django 4.1.7 on 2023-03-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eBirth_reg", "0004_gender_remove_birthregistration_delivered_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="birthregistration",
            name="date_issue",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
