# Generated by Django 4.1.7 on 2023-03-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eBirth_reg", "0005_alter_birthregistration_date_issue"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitaladminprofile",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
