# Generated by Django 4.1.7 on 2023-03-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eBirth_reg", "0006_hospitaladminprofile_pic"),
    ]

    operations = [
        migrations.RemoveField(model_name="hospitaladminprofile", name="pic",),
        migrations.AddField(
            model_name="hospitalprofile",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
