# Generated by Django 4.1.7 on 2023-06-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eBirth_reg", "0007_remove_hospitaladminprofile_pic_hospitalprofile_pic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospitalprofile", old_name="pic", new_name="signature",
        ),
    ]
