# Generated by Django 5.0.6 on 2024-05-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eBirth_reg", "0009_deathregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deathregistration",
            name="date_of_death",
            field=models.DateTimeField(),
        ),
    ]
