# Generated by Django 5.0.6 on 2024-05-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eBirth_reg", "0010_alter_deathregistration_date_of_death"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deathregistration",
            name="age_at_death",
            field=models.CharField(max_length=4),
        ),
    ]
