# Generated by Django 5.0.6 on 2024-05-15 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eBirth_reg", "0011_alter_deathregistration_age_at_death"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathregistration",
            name="birth_id",
            field=models.ForeignKey(
                default="7f61a70247c54d5fafaf11a7147aad9f",
                on_delete=django.db.models.deletion.CASCADE,
                to="eBirth_reg.birthregistration",
            ),
            preserve_default=False,
        ),
    ]
