# Generated by Django 4.1.7 on 2023-03-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eBirth_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_hospital_admin",
            field=models.BooleanField(default=False),
        ),
    ]
