# Generated by Django 4.1.7 on 2023-06-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eBirth_auth", "0004_user_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pic",
            field=models.ImageField(
                blank=True, default="img/user.png", null=True, upload_to="uploads/"
            ),
        ),
    ]
